// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr9LehRWZZbY2KuCR4iLBkkSPM6Mm_5QY',
    appId: '1:677636470647:web:92ea03f90776d18c6d1372',
    messagingSenderId: '677636470647',
    projectId: 'helpexfyp',
    authDomain: 'helpexfyp.firebaseapp.com',
    storageBucket: 'helpexfyp.appspot.com',
    measurementId: 'G-8MS1479W89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU8Jl12xCMrctssVUet5KZ04tmcblrKc8',
    appId: '1:677636470647:android:e899b8079e62a6b26d1372',
    messagingSenderId: '677636470647',
    projectId: 'helpexfyp',
    storageBucket: 'helpexfyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkjF4dIdUTHC6kqh3yA7f9RXuuh51kmxU',
    appId: '1:677636470647:ios:896dea836a6ec5236d1372',
    messagingSenderId: '677636470647',
    projectId: 'helpexfyp',
    storageBucket: 'helpexfyp.appspot.com',
    iosClientId: '677636470647-vu9sonblrl07sdbb102444n37tqtv8lp.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpex',
  );
}
